export const mensagensCampeonato = {
  'pt-BR': {
    carregando: 'Carregando…',
    central: 'Central do campeonato', classificacao: 'Classificação', jogos: 'Jogos', estatisticas: 'Estatísticas', regulamento: 'Regulamento',
    clubes: 'Clubes', encerrados: 'Jogos encerrados', gols: 'Gols', media: 'Gols por jogo', empates: 'Empates',
    rodada: 'Rodada', anterior: 'Rodada anterior', proxima: 'Próxima rodada', proximos: 'Próximos jogos', verJogos: 'Ver todos os jogos',
    semJogos: 'Nenhum jogo nesta seleção.', semTabela: 'A classificação aparece quando os clubes forem confirmados.',
    semEventos: 'Ainda não há registros para este ranking.', semAgenda: 'A próxima partida ainda não foi agendada.',
    artilharia: 'Artilharia', assistencias: 'Assistências', amarelos: 'Cartões amarelos', vermelhos: 'Cartões vermelhos',
    fonte: 'Estatísticas de partidas encerradas. Os rankings dependem dos eventos registrados pela organização.',
    falhaEventos: 'Não foi possível carregar os rankings de jogadores.', tentar: 'Tentar novamente',
    atleta: 'Jogador', clube: 'Clube', total: 'Total', grupo: 'Grupo', todos: 'Todos os clubes', filtrar: 'Filtrar jogos por clube',
    ataque: 'Melhores ataques', defesa: 'Defesas menos vazadas', semEstatisticas: 'As estatísticas aparecem após o primeiro resultado confirmado.',
    ultimos: 'Últimos 5', V: 'Vitória', E: 'Empate', D: 'Derrota',
    legenda: 'P: pontos · J: jogos · V: vitórias · E: empates · D: derrotas · GP: gols pró · GC: gols contra · SG: saldo · %: aproveitamento',
    ordem: 'Ordem oficial do campeonato. Consulte os critérios no regulamento.',
    voltar: 'Voltar', atualizar: 'Atualizar', atualizado: 'Atualizado às', aDefinir: 'A definir', semRegulamento: 'Regulamento ainda não informado.',
    GRUPOS: 'Fase de grupos', FASE_GRUPOS: 'Fase de grupos', PONTOS_CORRIDOS: 'Pontos corridos', MATA_MATA: 'Mata-mata', OITAVAS: 'Oitavas de final', QUARTAS: 'Quartas de final', SEMIFINAL: 'Semifinal', FINAL: 'Final',
  },
  en: {
    carregando: 'Loading…',
    central: 'Competition centre', classificacao: 'Standings', jogos: 'Matches', estatisticas: 'Statistics', regulamento: 'Rules',
    clubes: 'Clubs', encerrados: 'Completed matches', gols: 'Goals', media: 'Goals per match', empates: 'Draws',
    rodada: 'Matchweek', anterior: 'Previous matchweek', proxima: 'Next matchweek', proximos: 'Upcoming matches', verJogos: 'View all matches',
    semJogos: 'No matches in this selection.', semTabela: 'Standings will appear once clubs are confirmed.',
    semEventos: 'No events have been recorded for this ranking yet.', semAgenda: 'The next match has not been scheduled yet.',
    artilharia: 'Top scorers', assistencias: 'Assists', amarelos: 'Yellow cards', vermelhos: 'Red cards',
    fonte: 'Statistics from completed matches. Rankings depend on events recorded by the organisers.',
    falhaEventos: 'Player rankings could not be loaded.', tentar: 'Try again',
    atleta: 'Player', clube: 'Club', total: 'Total', grupo: 'Group', todos: 'All clubs', filtrar: 'Filter matches by club',
    ataque: 'Best attacks', defesa: 'Best defences', semEstatisticas: 'Statistics will appear after the first confirmed result.',
    ultimos: 'Last 5', V: 'Win', E: 'Draw', D: 'Loss',
    legenda: 'P: points · J: played · V: wins · E: draws · D: losses · GP: goals for · GC: goals against · SG: goal difference · %: points percentage',
    ordem: 'Official competition order. Check the rules for tiebreakers.',
    voltar: 'Back', atualizar: 'Refresh', atualizado: 'Updated at', aDefinir: 'To be announced', semRegulamento: 'Rules have not been published yet.',
    GRUPOS: 'Group stage', FASE_GRUPOS: 'Group stage', PONTOS_CORRIDOS: 'League', MATA_MATA: 'Knockout', OITAVAS: 'Round of 16', QUARTAS: 'Quarter-finals', SEMIFINAL: 'Semi-finals', FINAL: 'Final',
  },
}
