/**
 * Idiomas do site: português do Brasil (padrão) e inglês.
 *
 * A escolha fica no localStorage. Quem nunca escolheu cai no pt-BR mesmo que o
 * navegador esteja em outro idioma — o público do FutPlay é brasileiro, e
 * adivinhar pelo navegador erraria para quem usa o sistema em inglês aqui.
 *
 * O endereço, porém, manda mais que a preferência salva: abrir `/en/tournaments`
 * mostra inglês para qualquer visitante. É o que permite indexar as duas
 * versões — e o rastreador do Google não tem localStorage para consultar.
 */

import { createI18n } from 'vue-i18n'
import { idiomaDoCaminho } from './seo'

export const IDIOMAS = [
  { codigo: 'pt-BR', rotulo: 'Português', bandeira: '🇧🇷' },
  { codigo: 'en', rotulo: 'English', bandeira: '🇺🇸' },
] as const

export type CodigoIdioma = (typeof IDIOMAS)[number]['codigo']

const CHAVE = 'futplay:idioma'

export function idiomaSalvo(): CodigoIdioma {
  try {
    const v = localStorage.getItem(CHAVE)
    if (v && IDIOMAS.some((i) => i.codigo === v)) return v as CodigoIdioma
  } catch {
    // Navegação privada pode recusar o localStorage; o padrão resolve.
  }
  return 'pt-BR'
}

export function salvarIdioma(codigo: CodigoIdioma) {
  try {
    localStorage.setItem(CHAVE, codigo)
  } catch {
    /* segue com o idioma em memória */
  }
  document.documentElement.lang = codigo
}

/** Idioma da primeira renderização: o da URL aberta, com a preferência salva como reserva. */
export function idiomaInicial(): CodigoIdioma {
  if (typeof location === 'undefined') return 'pt-BR'
  return idiomaDoCaminho(location.pathname) === 'en' ? 'en' : idiomaSalvo()
}

/**
 * Troca o idioma em uso.
 *
 * `persistir: false` é o caso do roteador, que só está refletindo o endereço
 * aberto: uma visita a `/en` vinda de um link não deve reescrever a escolha de
 * quem usa o site em português.
 */
export function definirIdioma(codigo: CodigoIdioma, { persistir = true } = {}) {
  if (i18n.global.locale.value !== codigo) i18n.global.locale.value = codigo
  if (typeof document !== 'undefined') document.documentElement.lang = codigo
  if (persistir) salvarIdioma(codigo)
}

const ptBR = {
  marca: 'FutPlay',
  nav: {
    inicio: 'Início',
    peladas: 'Peladas',
    campeonatos: 'Campeonatos',
    amistosos: 'Amistosos',
    clubes: 'Clubes',
    agenda: 'Agenda',
    sorteio: 'Sorteio',
    entrar: 'Entrar',
    sair: 'Sair',
    minhaConta: 'Minha conta',
  },
  home: {
    appSelo: 'FutPlay para Android',
    primeiroPasso: 'Instale e entre com o Google',
    primeiroPassoTexto: 'Baixe na Google Play e use sua conta para começar a jogar.',
    appTitulo: 'Sua próxima pelada começa no FutPlay.',
    appTexto: 'Leve seu futebol no bolso. Encontre peladas, reúna seu time e acompanhe cada rodada do campeonato pelo aplicativo.',
    instalar: 'Instalar o FutPlay',
    loja: 'Disponível no Google Play',
    chamadaMobile: 'Seu futebol, no bolso.',
    titulo: 'O jeito mais fácil de organizar sua pelada',
    subtitulo:
      'Monte times equilibrados, acompanhe rankings, organize campeonatos e marque amistosos. Tudo em um lugar só.',
    entrar: 'Entrar com Google',
    verPeladas: 'Ver peladas próximas',
    baixarApp: 'Baixar o aplicativo',
    explorarWeb: 'Explorar pelo navegador',
    recursos: {
      titulo: 'Tudo que sua pelada precisa',
      sorteio: {
        titulo: 'Times equilibrados',
        texto: 'Sorteio por overall, com coletes e reservas — sem discussão antes do jogo.',
      },
      ranking: {
        titulo: 'Rankings e prêmios',
        texto: 'Ranking da pelada, da temporada e vitalício. Pódio com artilheiro, maestro e muralha.',
      },
      campeonato: {
        titulo: 'Campeonatos completos',
        texto: 'Grupos, mata-mata, tabela e súmula. A chave inteira gerada de uma vez.',
      },
      amistoso: {
        titulo: 'Amistosos entre clubes',
        texto: 'Desafie um clube direto ou publique um desafio aberto e espere quem topar.',
      },
    },
    comoFunciona: 'Como funciona',
    passos: {
      um: { titulo: 'Entre com o Google', texto: 'Se você já usa o app, seu perfil aparece aqui na hora.' },
      dois: { titulo: 'Escolha sua pelada', texto: 'Procure por cidade, peça para entrar no grupo e pronto.' },
      tres: { titulo: 'Jogue e acompanhe', texto: 'Scouts, ranking e prêmios atualizados a cada rodada.' },
    },
    mesmaConta: 'Mesma conta do aplicativo',
    mesmaContaTexto:
      'O site e o app compartilham a mesma conta. Entre com o Google e seus grupos, clubes e campeonatos já estarão aqui.',
  },
  explorar: {
    titulo: 'Comece por aqui',
    texto: 'As quatro ferramentas do FutPlay, abertas e sem conta para olhar.',
    sorteio: 'Sorteador de times de futebol',
    sorteioTexto: 'Divida o grupo em times equilibrados em segundos.',
    peladas: 'Peladas perto de você',
    peladasTexto: 'Procure por cidade e peça para entrar no grupo.',
    campeonatos: 'Campeonatos amadores',
    campeonatosTexto: 'Grupos, mata-mata, tabela e artilharia.',
    amistosos: 'Amistosos entre clubes',
    amistososTexto: 'Desafie um time ou publique um desafio aberto.',
  },
  faq: { titulo: 'Perguntas frequentes' },
  entrar: {
    titulo: 'Entrar no FutPlay',
    texto: 'Use sua conta Google. É a mesma do aplicativo.',
    botao: 'Continuar com Google',
    erro: 'Não foi possível entrar. Tente novamente.',
  },
  cadastro: {
    titulo: 'Complete seu cadastro',
    texto: 'Só precisamos de alguns dados para montar seu perfil de jogador.',
    nome: 'Nome',
    posicao: 'Posição',
    idade: 'Idade',
    peso: 'Peso (kg)',
    peDominante: 'Pé dominante',
    foto: 'Foto',
    trocarFoto: 'Escolher foto',
    salvar: 'Salvar e continuar',
    salvando: 'Salvando…',
  },
  sorteio: {
    selo: 'Ferramenta do organizador',
    h1: 'Sorteador de times de futebol grátis',
    lead: 'Cole um jogador por linha, defina o tamanho das equipes e faça o sorteio para sua pelada. Os nomes repetidos são removidos; quem sobrar forma o próximo time.',
    jogadores: 'Jogadores',
    exemplo: 'Ana\nBruno\nCarlos',
    meta: 'Meta de jogadores por time',
    porTime: '{n} jogadores',
    sortear: 'Sortear times',
    resultado: 'Resultado',
    copiar: 'Copiar',
    vazio: 'O resultado aparecerá aqui.',
    time: 'Time {n}',
    minimo: 'Informe pelo menos dois jogadores.',
    semCopiar: 'Não foi possível copiar. Selecione o resultado manualmente.',
    cabecalhoCopia: 'FutPlay — sorteio de times',
    comoTitulo: 'Como sortear times equilibrados?',
    comoTexto: 'Distribua goleiros e jogadores que atuam na mesma posição antes do sorteio. Depois, use a ferramenta para dividir os demais nomes e ajuste somente se houver um desequilíbrio evidente.',
    peladaTitulo: 'Sorteio de times para pelada',
    peladaTexto: 'O resultado pode ser copiado e enviado ao grupo. Para guardar jogadores, organizar jogos e acompanhar resultados, use o FutPlay.',
  },
  peladas: {
    h1: 'Como organizar peladas de futebol',
    lead: 'Encontre jogos, confirme jogadores, acompanhe vagas e reúna o seu grupo de futebol amador.',
    titulo: 'Peladas',
    proximas: 'Peladas próximas',
    minhas: 'Minhas peladas',
    buscarCidade: 'Buscar por cidade',
    vazio: 'Nenhuma pelada encontrada.',
    pedirEntrada: 'Pedir para entrar',
    sair: 'Sair da pelada',
    saindo: 'Saindo…',
    pedidoEnviado: 'Pedido enviado',
    jaSouMembro: 'Você já participa',
    quando: 'Quando',
    onde: 'Onde',
    valor: 'Valor',
    jogadores: 'Jogadores',
    inscritos: 'inscritos',
    jogoMarcado: 'Jogo marcado',
    gratis: 'Grátis',
  },
  campeonatos: {
    h1: 'Gerenciador de campeonatos de futebol amador',
    lead: 'Crie competições, acompanhe jogos, fases, tabelas e classificações do seu campeonato.',
    titulo: 'Campeonatos',
    meus: 'Meus campeonatos',
    descobrir: 'Descobrir',
    vazio: 'Nenhum campeonato por aqui ainda.',
    chamada: 'Tabela, jogos, artilharia e chaveamento de cada competição.',
    classificacao: 'Classificação',
    jogos: 'Jogos',
    regulamento: 'Regulamento',
    inscrever: 'Inscrever meu clube',
    formato: 'Formato',
    fase: 'Fase',
    grupo: 'Grupo',
    rodada: 'Rodada',
  },
  tabela: {
    posicao: '#',
    clube: 'Clube',
    pontos: 'P',
    jogos: 'J',
    vitorias: 'V',
    empates: 'E',
    derrotas: 'D',
    golsPro: 'GP',
    golsContra: 'GC',
    saldo: 'SG',
  },
  amistosos: {
    titulo: 'Amistosos',
    meus: 'Meus',
    recebidos: 'Recebidos',
    abertos: 'Abertos',
    todos: 'Todos',
    historico: 'Histórico',
    vazio: 'Nenhum amistoso neste filtro.',
    chamada: 'Desafios abertos e partidas marcadas entre clubes.',
    candidatar: 'Candidatar meu clube',
    candidatado: 'Candidatura enviada',
    versus: 'x',
    aguardandoAdversario: 'Aguardando adversário',
  },
  clubes: {
    titulo: 'Clubes',
    meus: 'Meus clubes',
    buscar: 'Buscar por cidade',
    vazio: 'Nenhum clube encontrado.',
    chamada: 'Encontre clubes da sua cidade e peça para entrar.',
    membros: 'atletas',
    sobre: 'Sobre',
    entrar: 'Pedir para entrar',
  },
  conta: {
    titulo: 'Minha conta',
    dados: 'Dados do jogador',
    atributos: 'Atributos',
    salvar: 'Salvar alterações',
    salvo: 'Alterações salvas.',
    sair: 'Sair da conta',
  },
  chat: {
    titulo: 'Conversa',
    vazio: 'Nenhuma mensagem ainda. Comece a conversa.',
    escreva: 'Escreva uma mensagem…',
    enviar: 'Enviar',
  },
  criar: {
    campeonato: 'Criar campeonato',
    amistoso: 'Marcar amistoso',
    nome: 'Nome do campeonato',
    formato: 'Formato',
    cidade: 'Cidade',
    regulamento: 'Regulamento',
    inicio: 'Começa em',
    fim: 'Termina em',
    inscricaoInicio: 'Inscrições abrem',
    inscricaoFim: 'Inscrições fecham',
    grupos: 'Quantidade de grupos',
    classificados: 'Classificados por grupo',
    clubeOrganizador: 'Clube organizador',
    mandante: 'Meu clube',
    visitante: 'Adversário',
    tipoDesafio: 'Tipo de desafio',
    aberto: 'Aberto — qualquer clube pode se candidatar',
    direto: 'Direto — escolho o adversário',
    dataHora: 'Data e hora',
    local: 'Local',
    endereco: 'Endereço',
    estado: 'Estado',
    observacoes: 'Observações',
    salvar: 'Criar',
    salvando: 'Criando…',
    semClube: 'Você precisa de um clube para isso. Crie um no aplicativo primeiro.',
  },
  status: {
    RASCUNHO: 'Rascunho',
    INSCRICOES_ABERTAS: 'Inscrições abertas',
    GERACAO_TABELA: 'Gerando tabela',
    EM_ANDAMENTO: 'Em andamento',
    ATIVO: 'Ativo',
    FASE_GRUPOS: 'Fase de grupos',
    MATA_MATA: 'Mata-mata',
    OITAVAS: 'Oitavas',
    QUARTAS: 'Quartas',
    SEMIFINAL: 'Semifinal',
    FINAL: 'Final',
    CONCLUIDO: 'Concluído',
    FINALIZADO: 'Finalizado',
    CANCELADO: 'Cancelado',
    PROPOSTO: 'Proposto',
    EM_NEGOCIACAO: 'Em negociação',
    ACEITO: 'Aceito',
    PLACAR_PENDENTE: 'Placar pendente',
    RECUSADO: 'Recusado',
    AGENDADO: 'Agendado',
    CONFIRMADO: 'Confirmado',
    PENDENTE: 'Pendente',
  },
  comum: {
    carregando: 'Carregando…',
    erro: 'Algo deu errado.',
    tentarNovamente: 'Tentar novamente',
    voltar: 'Voltar',
    cidade: 'Cidade',
    buscar: 'Buscar',
    limpar: 'Limpar',
    ver: 'Ver',
    naoInformado: 'Não informado',
    idioma: 'Idioma',
    entrarParaParticipar: 'Entrar para participar',
    visitando: 'Você está vendo o FutPlay sem conta. Entre com o Google para participar, criar e conversar.',
    entrarParaConversar: 'Entre para conversar',
    filtrarNaLista: 'Filtrar nesta lista',
    resultados: 'nenhum resultado | 1 resultado | {n} resultados',
  },
  rodape: {
    direitos: 'Todos os direitos reservados.',
    privacidade: 'Política de Privacidade',
    termos: 'Termos de Uso',
    legal: 'Avisos legais',
  },
}

const en: typeof ptBR = {
  marca: 'FutPlay',
  nav: {
    inicio: 'Home',
    peladas: 'Pickup games',
    campeonatos: 'Tournaments',
    amistosos: 'Friendlies',
    clubes: 'Clubs',
    agenda: 'Schedule',
    sorteio: 'Team draw',
    entrar: 'Sign in',
    sair: 'Sign out',
    minhaConta: 'My account',
  },
  home: {
    appSelo: 'FutPlay for Android',
    primeiroPasso: 'Install and sign in with Google',
    primeiroPassoTexto: 'Download from Google Play and use your account to get started.',
    appTitulo: 'Your next game starts with FutPlay.',
    appTexto: 'Take your football with you. Find pickup games, bring your team together and follow every tournament round in the app.',
    instalar: 'Install FutPlay',
    loja: 'Available on Google Play',
    chamadaMobile: 'Your football, on the go.',
    titulo: 'The easiest way to run your pickup game',
    subtitulo:
      'Build balanced teams, track rankings, run tournaments and schedule friendlies. All in one place.',
    entrar: 'Sign in with Google',
    verPeladas: 'Find games near you',
    baixarApp: 'Get the app',
    explorarWeb: 'Browse on the web',
    recursos: {
      titulo: 'Everything your game needs',
      sorteio: {
        titulo: 'Balanced teams',
        texto: 'Draw by overall rating, with bibs and substitutes — no arguing before kickoff.',
      },
      ranking: {
        titulo: 'Rankings and awards',
        texto: 'Match, season and all-time rankings. Podium with top scorer, playmaker and wall.',
      },
      campeonato: {
        titulo: 'Full tournaments',
        texto: 'Groups, knockout, table and match sheet. The whole bracket generated at once.',
      },
      amistoso: {
        titulo: 'Club friendlies',
        texto: 'Challenge a club directly or post an open challenge and wait for takers.',
      },
    },
    comoFunciona: 'How it works',
    passos: {
      um: { titulo: 'Sign in with Google', texto: 'Already use the app? Your profile shows up right away.' },
      dois: { titulo: 'Pick your game', texto: 'Search by city, ask to join the group, and you are in.' },
      tres: { titulo: 'Play and follow along', texto: 'Stats, rankings and awards updated every round.' },
    },
    mesmaConta: 'Same account as the app',
    mesmaContaTexto:
      'The site and the app share one account. Sign in with Google and your groups, clubs and tournaments are already here.',
  },
  explorar: {
    titulo: 'Start here',
    texto: 'The four FutPlay tools, open to browse without an account.',
    sorteio: 'Random soccer team generator',
    sorteioTexto: 'Split your group into balanced teams in seconds.',
    peladas: 'Pickup games near you',
    peladasTexto: 'Search by city and ask to join the group.',
    campeonatos: 'Amateur tournaments',
    campeonatosTexto: 'Groups, knockout, standings and top scorers.',
    amistosos: 'Club friendlies',
    amistososTexto: 'Challenge a team or post an open challenge.',
  },
  faq: { titulo: 'Frequently asked questions' },
  entrar: {
    titulo: 'Sign in to FutPlay',
    texto: 'Use your Google account — the same one as the app.',
    botao: 'Continue with Google',
    erro: 'Could not sign in. Please try again.',
  },
  cadastro: {
    titulo: 'Complete your profile',
    texto: 'We just need a few details to set up your player profile.',
    nome: 'Name',
    posicao: 'Position',
    idade: 'Age',
    peso: 'Weight (kg)',
    peDominante: 'Dominant foot',
    foto: 'Photo',
    trocarFoto: 'Choose photo',
    salvar: 'Save and continue',
    salvando: 'Saving…',
  },
  sorteio: {
    selo: 'Organizer tool',
    h1: 'Free random soccer team generator',
    lead: 'Paste one player per line, set how many per side and draw the teams for your game. Repeated names are dropped; whoever is left over forms the next team.',
    jogadores: 'Players',
    exemplo: 'Anna\nBruno\nCharlie',
    meta: 'Target players per team',
    porTime: '{n} players',
    sortear: 'Draw teams',
    resultado: 'Result',
    copiar: 'Copy',
    vazio: 'The result will show up here.',
    time: 'Team {n}',
    minimo: 'Enter at least two players.',
    semCopiar: 'Could not copy. Select the result manually.',
    cabecalhoCopia: 'FutPlay — team draw',
    comoTitulo: 'How do you draw balanced teams?',
    comoTexto: 'Split the goalkeepers and the players who share a position before drawing. Then use the tool to divide the remaining names, and only adjust if there is an obvious imbalance.',
    peladaTitulo: 'Team draw for pickup games',
    peladaTexto: 'The result can be copied and sent to the group. To keep your players, organize matches and follow results, use FutPlay.',
  },
  peladas: {
    h1: 'How to organize pickup soccer games',
    lead: 'Find matches, confirm players, track open spots and bring your amateur football group together.',
    titulo: 'Pickup games',
    proximas: 'Games near you',
    minhas: 'My games',
    buscarCidade: 'Search by city',
    vazio: 'No games found.',
    pedirEntrada: 'Ask to join',
    sair: 'Leave pickup game',
    saindo: 'Leaving…',
    pedidoEnviado: 'Request sent',
    jaSouMembro: 'You already play here',
    quando: 'When',
    onde: 'Where',
    valor: 'Fee',
    jogadores: 'Players',
    inscritos: 'signed up',
    jogoMarcado: 'Match scheduled',
    gratis: 'Free',
  },
  campeonatos: {
    h1: 'Amateur football tournament manager',
    lead: 'Create competitions and follow the fixtures, stages, tables and standings of your tournament.',
    titulo: 'Tournaments',
    meus: 'My tournaments',
    descobrir: 'Discover',
    vazio: 'No tournaments here yet.',
    chamada: 'Standings, fixtures, top scorers and bracket for every competition.',
    classificacao: 'Standings',
    jogos: 'Matches',
    regulamento: 'Rules',
    inscrever: 'Enter my club',
    formato: 'Format',
    fase: 'Stage',
    grupo: 'Group',
    rodada: 'Round',
  },
  tabela: {
    posicao: '#',
    clube: 'Club',
    pontos: 'Pts',
    jogos: 'P',
    vitorias: 'W',
    empates: 'D',
    derrotas: 'L',
    golsPro: 'GF',
    golsContra: 'GA',
    saldo: 'GD',
  },
  amistosos: {
    titulo: 'Friendlies',
    meus: 'Mine',
    recebidos: 'Received',
    abertos: 'Open',
    todos: 'All',
    historico: 'History',
    vazio: 'No friendlies in this filter.',
    chamada: 'Open challenges and scheduled matches between clubs.',
    candidatar: 'Offer my club',
    candidatado: 'Offer sent',
    versus: 'vs',
    aguardandoAdversario: 'Waiting for an opponent',
  },
  clubes: {
    titulo: 'Clubs',
    meus: 'My clubs',
    buscar: 'Search by city',
    vazio: 'No clubs found.',
    chamada: 'Find clubs in your city and ask to join.',
    membros: 'players',
    sobre: 'About',
    entrar: 'Ask to join',
  },
  conta: {
    titulo: 'My account',
    dados: 'Player details',
    atributos: 'Attributes',
    salvar: 'Save changes',
    salvo: 'Changes saved.',
    sair: 'Sign out',
  },
  chat: {
    titulo: 'Chat',
    vazio: 'No messages yet. Start the conversation.',
    escreva: 'Write a message…',
    enviar: 'Send',
  },
  criar: {
    campeonato: 'Create tournament',
    amistoso: 'Schedule friendly',
    nome: 'Tournament name',
    formato: 'Format',
    cidade: 'City',
    regulamento: 'Rules',
    inicio: 'Starts on',
    fim: 'Ends on',
    inscricaoInicio: 'Registration opens',
    inscricaoFim: 'Registration closes',
    grupos: 'Number of groups',
    classificados: 'Qualifiers per group',
    clubeOrganizador: 'Host club',
    mandante: 'My club',
    visitante: 'Opponent',
    tipoDesafio: 'Challenge type',
    aberto: 'Open — any club can apply',
    direto: 'Direct — I pick the opponent',
    dataHora: 'Date and time',
    local: 'Venue',
    endereco: 'Address',
    estado: 'State',
    observacoes: 'Notes',
    salvar: 'Create',
    salvando: 'Creating…',
    semClube: 'You need a club for this. Create one in the app first.',
  },
  status: {
    RASCUNHO: 'Draft',
    INSCRICOES_ABERTAS: 'Registration open',
    GERACAO_TABELA: 'Building table',
    EM_ANDAMENTO: 'In progress',
    ATIVO: 'Active',
    FASE_GRUPOS: 'Group stage',
    MATA_MATA: 'Knockout',
    OITAVAS: 'Round of 16',
    QUARTAS: 'Quarter-finals',
    SEMIFINAL: 'Semi-finals',
    FINAL: 'Final',
    CONCLUIDO: 'Completed',
    FINALIZADO: 'Finished',
    CANCELADO: 'Cancelled',
    PROPOSTO: 'Proposed',
    EM_NEGOCIACAO: 'Negotiating',
    ACEITO: 'Accepted',
    PLACAR_PENDENTE: 'Score pending',
    RECUSADO: 'Declined',
    AGENDADO: 'Scheduled',
    CONFIRMADO: 'Confirmed',
    PENDENTE: 'Pending',
  },
  comum: {
    carregando: 'Loading…',
    erro: 'Something went wrong.',
    tentarNovamente: 'Try again',
    voltar: 'Back',
    cidade: 'City',
    buscar: 'Search',
    limpar: 'Clear',
    ver: 'View',
    naoInformado: 'Not provided',
    idioma: 'Language',
    entrarParaParticipar: 'Sign in to join',
    visitando: 'You are browsing FutPlay without an account. Sign in with Google to join, create and chat.',
    entrarParaConversar: 'Sign in to chat',
    filtrarNaLista: 'Filter this list',
    resultados: 'no results | 1 result | {n} results',
  },
  rodape: {
    direitos: 'All rights reserved.',
    privacidade: 'Privacy Policy',
    termos: 'Terms of Use',
    legal: 'Legal',
  },
}

export const i18n = createI18n({
  legacy: false,
  locale: idiomaInicial(),
  fallbackLocale: 'pt-BR',
  messages: { 'pt-BR': ptBR, en },
})
