/**
 * Textos da gestão de pelada e dos filtros da lista, em escopo local.
 *
 * Mesma escolha de `idioma-campeonato.ts`: são termos que só existem nestas
 * telas, e mantê-los aqui evita inchar o `idioma.ts`, que carrega em toda página.
 */
export const mensagensGestao = {
  'pt-BR': {
    gestao: 'Gestão da pelada',
    gestaoSub: 'Você administra esta pelada',
    pedidos: 'Pedidos de entrada',
    semPedidos: 'Nenhum pedido pendente.',
    aprovar: 'Aprovar',
    recusar: 'Recusar',
    elenco: 'Elenco',
    remover: 'Remover',
    promover: 'Tornar admin',
    dono: 'Dono',
    admin: 'Admin',
    membro: 'Atleta',
    pendente: 'Pendente',
    editar: 'Editar informações',
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    salvo: 'Informações atualizadas.',
    campoLocal: 'Local',
    campoDia: 'Dia da semana',
    campoInicio: 'Início',
    campoFim: 'Fim',
    campoValor: 'Valor por pessoa',
    campoVagas: 'Vagas',
    campoPorTime: 'Jogadores por time',
    campoTipo: 'Tipo de jogo',
    vagas: 'Vagas',
    vagasRestantes: '{n} de {total} vagas livres',
    lotada: 'Pelada lotada',
    entrar: 'Entrar na pelada',
    sair: 'Sair da pelada',
    pedirEntrada: 'Pedir para entrar',
    pedidoEnviado: 'Pedido enviado. Aguarde a aprovação.',
    jaMembro: 'Você joga aqui',
    confirmarSair: 'Sair desta pelada?',
    confirmarRemover: 'Remover {nome} da pelada?',
    verNoMapa: 'Ver no mapa',
    porTime: 'por time',
    perto: 'Perto de mim',
    buscandoLocal: 'Localizando…',
    raio: 'Raio',
    filtroTipo: 'Tipo',
    filtroDia: 'Dia',
    precoAte: 'Preço até',
    comVaga: 'Só com vaga',
    limparFiltros: 'Limpar filtros',
    todos: 'Todos',
    semLocalizacao: 'Ative a localização para ver distância e ordenar por perto.',
  },
  en: {
    gestao: 'Match management',
    gestaoSub: 'You manage this match',
    pedidos: 'Join requests',
    semPedidos: 'No pending requests.',
    aprovar: 'Approve',
    recusar: 'Decline',
    elenco: 'Squad',
    remover: 'Remove',
    promover: 'Make admin',
    dono: 'Owner',
    admin: 'Admin',
    membro: 'Player',
    pendente: 'Pending',
    editar: 'Edit details',
    salvar: 'Save',
    cancelar: 'Cancel',
    salvo: 'Details updated.',
    campoLocal: 'Venue',
    campoDia: 'Day of week',
    campoInicio: 'Start',
    campoFim: 'End',
    campoValor: 'Price per player',
    campoVagas: 'Spots',
    campoPorTime: 'Players per side',
    campoTipo: 'Match type',
    vagas: 'Spots',
    vagasRestantes: '{n} of {total} spots open',
    lotada: 'Match is full',
    entrar: 'Join match',
    sair: 'Leave match',
    pedirEntrada: 'Request to join',
    pedidoEnviado: 'Request sent. Wait for approval.',
    jaMembro: 'You play here',
    confirmarSair: 'Leave this match?',
    confirmarRemover: 'Remove {nome} from the match?',
    verNoMapa: 'View on map',
    porTime: 'per side',
    perto: 'Near me',
    buscandoLocal: 'Locating…',
    raio: 'Radius',
    filtroTipo: 'Type',
    filtroDia: 'Day',
    precoAte: 'Price up to',
    comVaga: 'Open spots only',
    limparFiltros: 'Clear filters',
    todos: 'All',
    semLocalizacao: 'Turn on location to see distance and sort by nearest.',
  },
}
